config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "users/:id" => "users#show", as: :user
  # resources :ingredients, only: [:]
  # Defines the root path route ("/")
  # root "posts#index"
  resources :recipes, only: %i[index show new create edit update] do
    resources :purchases, only: %i[new create]
    resources :ratings, only: %i[create update]
  end
  resources :ratings, only: [:edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipes, through: :recipe_ingredients
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :users, through: :purchases
  has_many :ratings
  has_one_attached :photo

  accepts_nested_attributes_for :recipe_ingredients

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 5 }
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :category, presence: true
  validates :number_of_people, numericality: { only_integer: true, greater_than: 0 }
  validates :instructions, presence: true, length: { minimum: 20 }

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :title, :description , :category ],
    associated_against: {
      ingredients: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
    }

  def average_rating_bis
    return 0 if ratings.empty?

    (ratings.pluck(:rating).sum / ratings.count.to_f).round(1)
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :unit, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :purchases
  has_many :purchased_recipes, through: :purchases, source: :recipe
  has_many :recipes
  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :user_name, :nationality])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :user_name, :nationality])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def new
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    recipe = Recipe.find(params[:recipe_id])

    purchase = Purchase.new()
    purchase.user = current_user
    purchase.recipe = recipe
    purchase.total_price = recipe.price
    if purchase.save
      redirect_to user_path(current_user)
    else
      render :new, status: 422
    end
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @rating = Rating.new(rating_params)
    @rating.recipe = @recipe
    @rating.user = current_user
    respond_to do |format|
      if @rating.save
        format.html { redirect_to recipe_path(@recipe) }
        format.json # Follows the classic Rails flow and look for a create.json view
      else
        format.html { render recipe_path(@recipe), status: :unprocessable_entity }
        format.json # Follows the classic Rails flow and look for a create.json view
      end
    end
  end

  def edit
    @rating = Rating.find(params[:id])
    @recipe = @rating.recipe
  end

  def update
    @rating = Rating.find(params[:id])
    @recipe = @rating.recipe
    @rating.update(rating_params)
    if @rating.save
      redirect_to recipe_path(@recipe)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:rating, :comment)
  end
end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
    @rating = Rating.new # for the form adding ratings
  end

  def index
    if params[:query].present?
      @query = params[:query]
      @recipes = params[:rating].present? ? order_recipes(params[:rating], params[:query]) : Recipe.global_search(params[:query]).reverse
    else
      @recipes = params[:rating].present? ? order_recipes(params[:rating]) : Recipe.all.reverse
    end
  end

  def new
    @recipe = Recipe.new
    @recipe.recipe_ingredients.new
  end

  def create
    @recipe = Recipe.new(recipes_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @recipe.recipe_ingredients
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipes_params)
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def order_recipes(keyword, query = nil)
    if query.nil?
      if keyword == "top"
        return Recipe.all.sort_by(&:average_rating_bis).reverse # changes need to be made here
      else
        return Recipe.all.sort_by(&:average_rating_bis)
      end
    else
      if keyword == "top"
        return Recipe.global_search(query).sort_by(&:average_rating_bis).reverse
      else
        return Recipe.global_search(query).sort_by(&:average_rating_bis)
      end
    end
  end

  def recipes_params
    params.require(:recipe).permit(:title, :description, :price, :category,
                                   :number_of_people, :instructions, :photo,
                                   recipe_ingredients_attributes: [:amount, :unit, :ingredient_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gourbetter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300&display=swap" rel="stylesheet">    <link href="https://fonts.googleapis.com/css2?family=Alice&family=Merriweather:wght@300&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="page-container">
      <div class="navbar-container"><%= render "shared/navbar" %></div>
      <%= yield %>
      <div class="footer-container"><%= render "shared/footer" %></div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%= image_path("banner-background.jpg") %>);">
  <div class="container">
    <%= image_tag("logo.png") %>
    <%= link_to("Find new recipes here!", recipes_path, class: "btn btn-warning btn-lg", style: "font-size:36px text-align:right margin-right:500px") %>
  </div>
</div>

<div class="card-container">
  <div class="text-container">
    <p>Discover a world of delectable delights with Gourbetter,<br /> your go-to destination for premium, curated recipes. Elevate your cooking experience, explore new flavors, and master the art of gastronomy with our carefully crafted collection.</p>
  </div>
  <h1>Why Gourbetter?</h1>
  <div class="card-all">
    <div class="card-info">
      <%# <img src="" alt="Picture of something"> %>
      <h2>Exclusive Recipes</h2>
      <p>Gain access to a diverse range of exclusive recipes crafted by renowned chefs and culinary experts. From gourmet meals to quick and easy dishes, Gourbetter has something for every palate.</p>
    </div>
    <div class="card-info">
      <%# <img src="" alt="Picture of something"> %>
      <h2>Ingredient Excellence</h2>
      <p>We believe in the power of quality ingredients. Each recipe on Gourbetter is designed to showcase the finest flavors, ensuring a delightful culinary journey with every dish you create.</p>
    </div>
    <div class="card-info">
      <%# <img src="" alt="Picture of something"> %>
      <h2>Step-by-Step Guidance</h2>
      <p>Whether you're a seasoned chef or a kitchen novice, our step-by-step instructions make it easy for you to follow along and create restaurant-worthy meals in the comfort of your home.</p>
    </div>
  </div>
  <h1>Get Started Today</h1>
  <div class="text-container">
    <p>Embark on a journey of flavor exploration.<br /> Join Gourbetter and transform your kitchen into a haven of gastronomic delights.<br /> Sign up now and savor the joy of cooking like never before.</p>
  </div>
  <%= link_to "Sign Up Now", new_user_registration_path, class: "btn btn-warning btn-lg" %>
</div>

app/views/purchases/new.html.erb
<div class="purc-container pb-2 mt-3 bg-white">
  <%= image_tag "logo_black.png", class: "logo d-block mx-auto my-4" %>
  <div class="content">
    <div class="d-flex justify-content-between">
      <div class="d-flex flex-column">
        <h2><%= @recipe.title %></h2>
        <p class="price">€ <%= @recipe.price %></p>
      </div>
      <%= button_to "Pay now", recipe_purchases_path(@recipe), class: "px-4 btn btn-yellow mx-auto" %>
    </div>

    <% if @recipe.photo.key.nil? %>
      <img class="recipe-pic d-block mx-auto" src="https://www.gutekueche.at/storage/media/recipe/134629/spaghetti-al-pomodoro.jpg" alt="spaguetti">
    <% else %>
      <%= cl_image_tag @recipe.photo.key, class: "recipe-pic d-block mx-auto" %>
    <% end %>
  </div>
</div>

app/views/ratings/_form.html.erb
<%= simple_form_for [recipe, rating], data: {
    insert_ratings_target: "form",
    action: "submit->insert-ratings#send"
  } do |f| %>
  <%= f.input :comment, placeholder: "Add your rating here...", as: :text, :input_html => { class: 'test', :cols => 3, :rows => 5 } %>

  <%= f.input :rating, as: :select, collection: (1..5), required: true %>

  <%= f.submit class: "btn btn-yellow mt-2" %>
<% end %>

app/views/ratings/_rating.html.erb
<div>
  <% rating.rating.times do %>
    <i class="fa fa-star star-color"></i>
  <% end %>
  <small><em class="text-muted"><%= distance_of_time_in_words_to_now(rating.created_at) %> ago</em></small>
  <p>by <%= rating.user.user_name %></p>
  <p class="mb-0"><%= rating.comment %>
    <span class="ml-3">
      <% if current_user == rating.user %>
        <%= link_to edit_rating_path(rating) do %>
          <i class="fa-regular fa-pen-to-square text-dark"></i>
        <% end %>
      <% end %>
    </span>
  </p>
  <hr>
</div>

app/views/ratings/edit.html.erb
<div class="container new_card">
  <h2 class="text-center">Second thoughts on this recipe?</h2>

  <%= render "form", rating: @rating, recipe: @recipe %>

</div>

app/views/recipes/_form.html.erb
  <div class="form-inputs">
    <%= simple_form_for(@recipe) do |f| %>
      <%= f.input :photo, as: :file %>
      <%= f.input :title %>
      <%= f.input :price %>
      <%= f.input :category %>
      <%= f.input :description, as: :text, :input_html => { :cols => 5, :rows => 5 } %>
      <%= f.input :number_of_people %>
      <div data-controller="add-ingredient-recipe">
        <div data-add-ingredient-recipe-target="list">
          <template class="d-flex ingredient-form">
            <div class="d-flex ingredient-form flex-wrap">
              <%= f.fields_for :recipe_ingredients do |ingredient| %>
              <div class="row">
                <div class="col-8">
                  <%= ingredient.input :ingredient_id, collection: Ingredient.all, value_method: :id %>
                </div>
                <div class="col-4 d-flex">
                <%= ingredient.input :amount %>
                <%= ingredient.input :unit %>
                </div>
                </div>
              <% end %>
            </div>
          </template>
          <div class="d-flex ingredient-form flex-wrap">
            <%= f.fields_for :recipe_ingredients do |ingredient| %>
            <div class="row">
              <div class="col-8">
                <%= ingredient.input :ingredient_id, collection: Ingredient.all, value_method: :id %>
              </div>
              <div class="col-4 d-flex">
              <%= ingredient.input :amount %>
              <%= ingredient.input :unit %>
              </div>
            <% end %>
          </div>
          </div>
        </div>

        <button class="btn btn-warning add-ingredient" data-action="click->add-ingredient-recipe#add">Add ingredient</button>
      </div>
      <%= f.input :instructions, as: :text, :input_html => { :cols => 5, :rows => 10 } %>
      <%= f.submit "Publish recipe", class: "btn btn-warning"  %>
    <% end %>
  </div>

app/views/recipes/edit.html.erb
<div class="container new_card">
  <h2 class="text-center">Edit recipe</h2>

  <%= render "form" %>

</div>

app/views/recipes/index.html.erb
<div class="container" data-controller="order-recipes-by">
  <div class="d-flex justify-content-between mt-2">
    <div>
      <% if @query %>
        <p>You searched for <strong><%= @query %></strong>. We found <%= @recipes.count %> recipes out of our <%= Recipe.count %> on our website.</p>
      <% else %>
        <p>All <%= @recipes.count %> recipes</p>
      <% end %>
    </div>
    <div>
      <select name="Order-By" data-action="change->order-recipes-by#orderRecipes">
        <option value="">Latest</option>
        <option value="top">Highest rating</option>
        <option value="lowest">Lowest rating</option>
      </select>
    </div>
  </div>
  <div class="cards" data-order-recipes-by-target="cards">
    <% @recipes.each do |recipe| %>
      <div class="card-trip">
        <% if recipe.photo.key.nil? %>
          <img src="https://www.gutekueche.at/storage/media/recipe/134629/spaghetti-al-pomodoro.jpg" alt="spaguetti">
        <% else %>
          <%= cl_image_tag recipe.photo.key, crop: :fill %>
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h4><%= recipe.title %> <span style="opacity: 0.6;">• <%= recipe.average_rating_bis %></span> <span>⭐</span></h4>
            <p><%= recipe.description %></p>
          </div>
        </div>
        <h4 class="card-trip-pricing">€ <%= recipe.price %></h4>
        <%= link_to("Read more", recipe_path(recipe), class: "read-more-button") %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container new_card small_container">
  <h2 class="text-center">New recipe</h2>

  <%= render "form" %>

</div>

app/views/recipes/show.html.erb
<%# Recipe show %>

<div class="container recipe-show justify-content-between d-flex bg-white mt-3">
  <%# if recipe has any ratings, display rating with stars %>
  <div class="container__text recipe-show-info p-0">
    <% if @recipe.ratings.any? %>
        <%# Recipe title %>
        <h1 class="text-dark"><%= @recipe.title %></h1>
        <%# Display stars %>
        <div class="container__text__star">
          <% if @recipe.average_rating_bis === 0 %>
            <span class="fa-regular fa-star"></span>
          <% end %>
          <% @recipe.average_rating_bis.round.times do %>
            <span class="fa fa-star"></span>
          <% end %>
          <span class="text-dark"><%= @recipe.average_rating_bis %>/5</span>
        </div>
      <%# if no ratings display this %>
    <% else %>
      <h1 class="text-dark"><%= @recipe.title %></h1>
      <p>No ratings</p>
    <% end %>

    <p><%= @recipe.description %></p>

    <%# Instructions and ingredients should be visible when user bought the recipe %>
    <% recipe_purchased = user_signed_in? && current_user.purchased_recipes.include?(@recipe) %>
    <% recipe_created = user_signed_in? && current_user.recipes.include?(@recipe) %>
    <% if recipe_purchased || recipe_created %>
      <h3>Ingredients:</h3>
      <ul>
        <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
          <% ingredient = Ingredient.find(recipe_ingredient.ingredient_id) %>
          <li class="text-dark"><%= ingredient.name %> - <%= recipe_ingredient.amount %> <%= recipe_ingredient.unit %></li>
        <% end %>
      </ul>
      <h3>Instructions:</h3>
      <p><%= @recipe.instructions %></p>
    <% end %>
  </div>

  <div class="recipe-show-img">
    <% if @recipe.photo.attached? %>
      <%= cl_image_tag @recipe.photo.key, height: 300, width: 400, crop: :fill %>
    <% else %>
      <%= image_tag "https://www.gutekueche.at/storage/media/recipe/134629/spaghetti-al-pomodoro.jpg", height: 300, width: 400 %>
    <% end %>

    <div class="container__text__timing justify-content-between">
      <div class="container__text__timing_time">
        <h2>Number of portions</h2>
        <p class="text-dark"><%= @recipe.number_of_people %></p>
      </div>
      <div class="container__text__timing_time">
        <h2>Chef</h2>
        <p class="text-dark"><%= @recipe.user.first_name %> <%= @recipe.user.last_name %></p>
      </div>
      <div class="container__text__timing_time">
        <h2>Price</h2>
        <p class="text-dark">€<%= @recipe.price %></p>
      </div>
    </div>
    <% if recipe_purchased || recipe_created %>
      <p>This recipe is on your <%= recipe_purchased ? '"Purchased"' : '"Created"' %> list! 😊 </p>
      <div class="d-flex">
        <%= link_to "Back", :back, class: "btn btn-outline-dark my-3 px-5" %>
      </div>
    <% else %>
      <%= link_to "Buy", new_recipe_purchase_path(@recipe), class: "btn btn-yellow px-5" %>
      <%= link_to "Back to recipes", recipes_path, class: "btn btn-outline-dark" %>
    <% end %>
  </div>

</div>

<%# Reviews  %>

<div class="container">
  <div data-controller="insert-ratings">
    <hr class="my-5">
    <div class="row">
    <% if user_signed_in? %>
      <div class="col-12 col-sm-6" data-insert-ratings-target="items">
        <h3>Ratings</h3>
        <% if @recipe.ratings.empty? %>
          <small><em class="text-muted">Be the first one to review this recipe</em></small>
        <% end %>
        <% @recipe.ratings.each do |rating| %>
          <%= render "ratings/rating", rating: rating %>
        <% end %>
      </div>
    <% end %>
    <% if recipe_purchased %>
      <div class="col-12 col-sm-6">
        <div class="bg-white rounded p-3">
          <h5>Add your review</h5>
          <%= render "ratings/form", rating: @rating, recipe: @recipe %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bd-footer py-1 py-md-2 mt-5 bg-dark border-body">
  <ul>
    <div class="d-flex align-items-center justify-content-between">
      <div class="contact col-4">
        <li><%= "Gourbetter by PayMe.Inc" %></li>
        <li>TEL. Not applicable</li>
        <li>@ Please don't</li>
      </div>
      <div class="phrase col-4">
        <li>The first recipe is always a fail</li>
      </div>
      <div class="col-4 d-flex justify-content-end">
        <li class="social-media">
          <%= link_to "https://github.com/" do %>
            <i class="fa-brands fa-square-github"></i>
          <% end %>
        </li>
        <li class="social-media">
          <%= link_to "https://www.instagram.com/" do %>
            <i class="fa-brands fa-square-instagram"></i>
          <% end %>
        </li>
        <li class="social-media">
          <%= link_to "https://twitter.com/" do %>
            <i class="fa-brands fa-square-x-twitter"></i>
          <% end %>
        </li>
      </div>
    </div>
  </ul>
</footer>

app/views/shared/_navbar.html.erb
<nav class="bg-dark border-body fixed-top p-1">
  <div class="container-fluid d-flex justify-content-between">
    <%# logo div %>
    <div class="d-flex container align-items-center">
      <%= link_to root_path do %>
        <%= image_tag "brand.png", width: "50" %>
      <% end %>
    </div>
    <%# search field div %>
    <div id="search-field" class="d-flex container align-items-center">
      <form class="d-flex flex-fill" action="/recipes" role="search">
        <input class="form-control me-2 flex-fill" type="search" placeholder="Search" aria-label="Search" name="query" value="">
        <button class="btn btn-warning" type="submit">Search</button>
      </form>
    </div>
    <%# buttons field %>
    <div class="d-flex container align-items-center justify-content-end">
      <ul class="d-flex flex-row mb-0">
        <% if user_signed_in? %>
          <button class="btn btn-warning dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Recipes
          </button>
          <ul class="dropdown-menu btn btn-dark bg-dark">
            <div class="d-flex row">
              <li><%= link_to "Show all", recipes_path %></li>
              <li><%= link_to "Create recipe", new_recipe_path %></li>
            </div>
          </ul>
          <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete} %>
          </li>
          <li class="nav-item">
            <%= link_to "My Profile", user_path(current_user) %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Recipes", recipes_path %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path %> / <%= link_to "Sign Up", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12'>

      <%# user card %>
      <div class="user_card">
        <div class="user_info">
          <h3><strong><%= @user.first_name %> <%= @user.last_name %></strong></h3>
          <p>📧 <%= @user.email %></p>
          <p>🌍 <%= @user.nationality %></p>
          <a href=<%= edit_user_registration_path %> class="btn btn-warning">Change my information</a>
        </div>
        <div>
            <p style="text-align: center;">User page of:</p>
          <h2><strong><%= @user.user_name %></strong></h2>
        </div>
        <img class="user_avatar" src="https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dXNlcnxlbnwwfHwwfHx8MA%3D%3D">
      </div>

    <div class="recipe_user_container">
      <%# purchased %>
      <div class="recipe_card col">
        <div class="card_menu_seperator">
          <h4>Purchased recipes</h4>
          <%= link_to("Find new recipe's", recipes_path, class: "btn btn-warning") %>
        </div>
        <div class="list-group">
          <% @user.purchases.each do |purchase| %>
            <%= link_to( recipe_path(purchase.recipe), class: "list-group-item list-group-item-action") do %>
            <div>
              <i class="fa-solid fa-kitchen-set" style="color: #ff9500; font-size: 30px;"></i><span style="font-size: 18px;"> - <%= purchase.recipe.title %></span>
            </div>
            <% end %>
          <% end %>
          <%# to change the color of the link, add class: active, add after class: aria-current="true"%>
          <%# <a class="list-group-item list-group-item-action disabled" aria-disabled="true">A disabled link item</a> %>
        </div>
      </div>

      <%# created %>
      <div class="recipe_card col">
        <div class="card_menu_seperator">
          <h4>Created recipes</h4>
          <%= link_to("Create new recipe", new_recipe_path , class: "btn btn-warning") %>
        </div>
        <div class="list-group">
          <% @user.recipes.each do |recipe| %>
            <%= link_to( recipe_path(recipe), class: "list-group-item list-group-item-action") do %>
              <i class="fa-solid fa-pen-to-square" style="color: #ff9500; font-size: 30px;"></i><span style="font-size: 18px;"> - <%= recipe.title %></i>
            <% end %>
          <% end %>
            <%# recipe_path[purchase.recipe] %>
          <%# to change the color of the link, add class: active, add after class: aria-current="true"%>
          <%# <a class="list-group-item list-group-item-action disabled" aria-disabled="true">A disabled link item</a> %>
        </div>
      </div>
<%# end %>
      </div>
    </div>
  </div>
</div>